### PR TITLE
fix(workspace): declare rust-version (MSRV 1.91.0) on every published crate (#398)

### PR DESCRIPTION
**Pull request by ohdearquant**
## Root cause

The 0.3.0 crates declared no `rust-version`, but `khive-pack-brain`'s `persist.rs` calls `str::floor_char_boundary`, which was unstable (`round_char_boundary` feature, rust-lang/rust#93743) before it stabilized. A consumer building with an older toolchain hit a raw `E0658` feature-gate error deep inside the dependency compile instead of cargo's clean "package requires rustc X.Y or newer" refusal.

## Determining the true MSRV

Bisected installed toolchains by compiling a minimal probe:

```rust
fn main() {
    let b = "hello".floor_char_boundary(3);
}
```

- rustc 1.90.0 → `error[E0658]: use of unstable library feature 'round_char_boundary'`
- rustc 1.91.0 → compiles cleanly

So `floor_char_boundary`/`ceil_char_boundary` stabilized in **1.91.0** — that's the workspace MSRV.

## Fix

- Added `rust-version = "1.91.0"` to `[workspace.package]` in `crates/Cargo.toml`.
- Added `rust-version.workspace = true` to every member crate that already inherits `edition.workspace = true` (37 crates — every published crate). `khive-merge` is intentionally excluded: it's a standalone forward-deployed workspace outside the main workspace's member list, with its own separate `[workspace.package]`.

## Verification

```
cargo check --workspace   # clean
```

## Test plan
- [x] `cargo check --workspace` passes with the declared MSRV
- [x] Bisection evidence (1.90.0 fails, 1.91.0 compiles) recorded in the commit message

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ohdearquant** [comment]
MSRV verification on the declared toolchain (requested at review):

```
cargo +1.91.0 check --workspace  (on this branch, isolated target dir)
Finished dev profile [unoptimized + debuginfo] target(s) in 43.25s
exit code 0
```

Full workspace compiles on 1.91.0, covering all floor_char_boundary users (khive-pack-brain, khive-runtime secret_gate). README prerequisite line updated to match the declared MSRV (436baa3a).

**Comment by ohdearquant** [comment]
## Automated code review — round 2

**VERDICT: APPROVE**

Manifest-only MSRV declaration. All 37 workspace members resolve to `rust-version = 1.91.0`; the excluded forward-deployed `khive-merge` is explicitly outside the publishing chain. Verified on the 1.91.0 toolchain:

- `cargo fmt --check`: pass
- strict clippy (`-D warnings`): pass
- MSRV-compat: Cargo cleanly rejects Rust 1.90 with the required-toolchain message; 1.91 builds
- Round-one hygiene fix (ASCII replacement in the workspace MSRV rationale) confirmed at head `fcf53c7`

No blockers, no outstanding fixes.

**Review by oceanwaves630 — APPROVED** [review]
Lane B on-sight approval per merge-flow v3: codex VERDICT: APPROVE verified on-PR (round 2) + CI green. No content read; subject to post-merge sampling audit.
